# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 14:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=512, unique=True)),
                ('created', models.DateField(default=datetime.date.today)),
                ('tooltip', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=512, unique=True)),
                ('created', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(default='', max_length=512)),
                ('views', models.IntegerField()),
                ('downloads', models.IntegerField()),
                ('versionInit', models.CharField(max_length=512)),
                ('client_ip', models.GenericIPAddressField(default='127.0.0.1')),
                ('keywords', models.CharField(default='', max_length=512)),
                ('category', models.ManyToManyField(through='data.CategoriesAmount', to='data.Category')),
            ],
            options={
                'verbose_name_plural': 'Workflows',
            },
        ),
        migrations.AddField(
            model_name='categoriesamount',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Category'),
        ),
        migrations.AddField(
            model_name='categoriesamount',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Workflow'),
        ),
    ]
