# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='json',
            field=models.CharField(default='hola', max_length=20000),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
