# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-07 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20181203_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tooltip',
            field=models.CharField(default='TOOLTIP', max_length=128),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='description',
            field=models.CharField(default='Descripcion', max_length=512),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='json',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='keywords',
            field=models.CharField(default='palabras clave', max_length=512),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='versionInit',
            field=models.CharField(default='1.0', max_length=512),
        ),
    ]
