# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-29 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20181207_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='delete_id',
            field=models.CharField(default='Holi esto es una prueba', max_length=40),
        ),
    ]
